# Generated by Django 3.0.5 on 2020-04-19 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basta', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='play',
            name='animal',
            field=models.CharField(blank=True, max_length=15, verbose_name='Animal'),
        ),
        migrations.AlterField(
            model_name='play',
            name='brand',
            field=models.TextField(blank=True, max_length=25, verbose_name='Brand'),
        ),
        migrations.AlterField(
            model_name='play',
            name='film',
            field=models.TextField(blank=True, max_length=40, verbose_name='Movie / Series'),
        ),
        migrations.AlterField(
            model_name='play',
            name='name',
            field=models.CharField(blank=True, max_length=15, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='play',
            name='obj',
            field=models.CharField(blank=True, max_length=15, verbose_name='Object'),
        ),
        migrations.AlterField(
            model_name='play',
            name='place',
            field=models.CharField(blank=True, max_length=15, verbose_name='City / Country'),
        ),
        migrations.AlterField(
            model_name='play',
            name='plant',
            field=models.CharField(blank=True, max_length=15, verbose_name='Flower / Fruit / Vegetable'),
        ),
        migrations.AlterField(
            model_name='play',
            name='surname',
            field=models.CharField(blank=True, max_length=15, verbose_name='Surname'),
        ),
    ]
