# Generated by Django 3.0.5 on 2020-04-19 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basta', '0003_auto_20200419_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='slug',
            field=models.SlugField(default='hello', max_length=30, unique=True),
            preserve_default=False,
        ),
    ]
