# Generated by Django 3.0.5 on 2020-04-19 18:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('basta', '0004_session_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='play',
            name='cur_round',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='play_set', to='basta.Round'),
        ),
        migrations.AlterField(
            model_name='play',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='play_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='round',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='round_set', to='basta.Session', verbose_name='Session'),
        ),
    ]
