# Generated by Django 3.0.5 on 2020-04-19 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basta', '0005_auto_20200419_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='round',
            name='number',
            field=models.PositiveIntegerField(),
        ),
    ]
