# Generated by Django 3.0.5 on 2020-04-20 22:26

from django.conf import settings
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('basta', '0006_auto_20200419_2303'),
    ]

    operations = [
        migrations.AddField(
            model_name='play',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Created at'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='play',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Modified at'),
        ),
        migrations.AddField(
            model_name='round',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Created at'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='round',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Modified at'),
        ),
        migrations.AlterField(
            model_name='round',
            name='letter',
            field=models.TextField(blank=True, editable=False, max_length=1, verbose_name='Letter'),
        ),
        migrations.AlterField(
            model_name='session',
            name='name',
            field=models.TextField(blank=True, max_length=50, verbose_name='Session name'),
        ),
        migrations.AlterUniqueTogether(
            name='play',
            unique_together={('cur_round', 'user')},
        ),
    ]
