# Generated by Django 3.0.5 on 2020-04-20 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basta', '0007_auto_20200421_0026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
