# Generated by Django 3.0.5 on 2020-04-21 07:36

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('basta', '0008_auto_20200421_0109'),
    ]

    operations = [
        migrations.RenameField(
            model_name='play',
            old_name='cur_round',
            new_name='round',
        ),
        migrations.AlterUniqueTogether(
            name='play',
            unique_together={('round', 'user')},
        ),
    ]
