# Generated by Django 3.0.5 on 2020-04-26 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basta', '0011_auto_20200424_0016'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.IntegerField(choices=[('name', 'Name'), ('surname', 'Surname'), ('plant', 'Flower / Fruit / Vegetable'), ('animal', 'Animal'), ('location', 'City / Country'), ('film', 'Movie / Series'), ('object', 'Object'), ('brand', 'Brand'), ('band', 'Musician / Band'), ('color', 'Color'), ('profession', 'Profession'), ('sport', 'Sport'), ('historical', 'Historical figure'), ('art', 'Monument / Art piece'), ('gifts', 'Gift / Present'), ('bad_habits', 'Bad habit'), ('reasons911', 'Reason to call 911'), ('food', 'Food'), ('athletes', 'Athlete'), ('fictional', 'Fictional character'), ('instruments', 'Instrument / Tool'), ('halloween', 'Halloween costume'), ('bodyparts', 'Body part')], unique=True, verbose_name='Category name')),
                ('default', models.BooleanField(default=False, verbose_name='Is default category?')),
            ],
        ),
        migrations.AlterModelOptions(
            name='play',
            options={'ordering': ['score'], 'verbose_name': 'Play', 'verbose_name_plural': 'Plays'},
        ),
        migrations.AlterModelOptions(
            name='round',
            options={'ordering': ['number'], 'verbose_name': 'Round', 'verbose_name_plural': 'Rounds'},
        ),
        migrations.AlterModelOptions(
            name='session',
            options={'ordering': ['-created_at'], 'verbose_name': 'Session', 'verbose_name_plural': 'Sessions'},
        ),
        migrations.RemoveField(
            model_name='play',
            name='animal',
        ),
        migrations.RemoveField(
            model_name='play',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='play',
            name='film',
        ),
        migrations.RemoveField(
            model_name='play',
            name='name',
        ),
        migrations.RemoveField(
            model_name='play',
            name='obj',
        ),
        migrations.RemoveField(
            model_name='play',
            name='place',
        ),
        migrations.RemoveField(
            model_name='play',
            name='plant',
        ),
        migrations.RemoveField(
            model_name='play',
            name='surname',
        ),
        migrations.AddField(
            model_name='session',
            name='random_categories',
            field=models.BooleanField(default=False, verbose_name='Random categories'),
        ),
        migrations.CreateModel(
            name='PlayCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modified at')),
                ('value', models.CharField(blank=True, max_length=50, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='basta.Category')),
                ('play', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='basta.Play')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='session',
            name='categories',
            field=models.ManyToManyField(related_name='_session_categories_+', to='basta.Category'),
        ),
    ]
