# Generated by Django 3.0.5 on 2020-04-27 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basta', '0014_initialize_categories'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='playcategory',
            options={'ordering': ['play', 'category']},
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('name', 'Name'), ('surname', 'Surname'), ('plant', 'Flower / Fruit / Vegetable'), ('animal', 'Animal'), ('location', 'City / Country'), ('film', 'Movie / Series'), ('object', 'Object'), ('brand', 'Brand'), ('band', 'Musician / Band'), ('color', 'Color'), ('profession', 'Profession'), ('sport', 'Sport'), ('historical', 'Historical figure'), ('art', 'Monument / Art piece'), ('gifts', 'Gift / Present'), ('bad_habits', 'Bad habit'), ('reasons911', 'Reason to call 911'), ('food', 'Food'), ('athletes', 'Athlete'), ('fictional', 'Fictional character'), ('instruments', 'Instrument / Tool'), ('halloween', 'Halloween costume'), ('bodyparts', 'Body part'), ('suicide', 'Dumb ways to die'), ('clothing', 'Cloting items'), ('drinks', 'Drink'), ('black', 'Thing that is black'), ('rivers', 'River'), ('boardgames', 'Board game'), ('author', 'Author'), ('song', 'Song')], max_length=15, unique=True, verbose_name='Category name'),
        ),
        migrations.AlterField(
            model_name='playcategory',
            name='value',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='session',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
