# Generated by Django 3.0.5 on 2020-05-03 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basta', '0016_initialize_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='play',
            name='score',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
