# Generated by Django 4.0.1 on 2022-01-30 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basta', '0018_initialize_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('name', 'Name'), ('surname', 'Surname'), ('plant', 'Flower / Fruit / Vegetable'), ('animal', 'Animal'), ('location', 'City / Country'), ('film', 'Movie / Series'), ('object', 'Object'), ('brand', 'Brand'), ('band', 'Musician / Band'), ('color', 'Color'), ('profession', 'Profession'), ('sport', 'Sport'), ('historical', 'Historical figure'), ('art', 'Monument / Art piece'), ('gifts', 'Gift / Present'), ('bad_habits', 'Bad habit'), ('reasons911', 'Reason to call 911'), ('food', 'Food'), ('athletes', 'Athlete'), ('fictional', 'Fictional character'), ('instruments', 'Instrument / Tool'), ('halloween', 'Halloween costume'), ('bodyparts', 'Body part'), ('suicide', 'Dumb ways to die'), ('clothing', 'Cloting items'), ('drinks', 'Drink'), ('black', 'Thing that is black'), ('rivers', 'River'), ('boardgames', 'Board game'), ('author', 'Author'), ('song', 'Song'), ('elements', 'Chemical element'), ('petnames', 'Pet name'), ('transportation', 'Means of transportation'), ('furniture', 'Furniture'), ('disease', 'Disease / Illness'), ('genres', 'Musical genre'), ('villains', 'Villain'), ('excuses', 'Excuses not to go to a party'), ('reasonsquitjob', 'Reasons to quit your job'), ('doatdate', 'Things to do on a date'), ('hobbies', 'Hobby / Activity'), ('uniforms', 'People in uniform'), ('literary', 'Work of literature')], max_length=15, unique=True, verbose_name='Category name'),
        ),
        migrations.AlterField(
            model_name='session',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='+', to='basta.Category'),
        ),
    ]
